x = 2
y <- 3
4 -> z
5->z
z<- 10 + 2
z <- 3 + rnorm(1)
?rnorm
rnorm(1)
x <- 1:10
x + 1
((2*x+1)/1.5)^2
animales <- c('perro','gato','fara')
frases <- "El gato se comió el fara"
numeros <- rep(x=1:3,3)/1.5
enteros <- seq(from=1,to=10,by=2)
complejos <- c(2i, 5i, 3i)
logicos <- c(T,F,TRUE,FALSE)
class(complejos)
prueba <- c
class(prueba)
grupo_altura <- factor(c("mediano","pequeño","grande","muy grande"),
                       levels=c("pequeño","mediano","grande","muy grande"))
ls()
ls.str()
vector1 <- seq(1:12)
matrix1 <- matrix(data=1:12,nrow=3,ncol=4)
vector1[6]
matrix1[2,3]
arreglo <- array(data = 1:12,dim=c(3,4,3))
arreglo[2,4,3]
vector1 <-rep(1:4,3)
vector2 <-seq(2,24,2)
arreglo <- array(data=c(vector1,vector2),dim=c(3,4,2))
arreglo[1,2,1]
arreglo[1,2,2]
data(iris)
iris$Sepal.Length
iris$Sepal.Length[36]
iris[36,1]
concatenar <- c(iris$Sepal.Length, iris$Sepal.Width)
minuevatabla <- cbind(iris$Sepal.Length, iris$Sepal.Width)
data <- read.csv('Matrix_Multivariate_Mega.csv')
data1 <- data[1:5,1:10]
write.csv(x = data1,file = 'Minimatriz.csv')
